# netlify.toml
[build]
  # El punto '.' significa que Netlify debe buscar los archivos
  # a desplegar en el directorio especificado como "Base directory" en su panel.
  publish = "." 
  
  # Comando de construcción: vacío si no necesitas compilar nada.
  command = "" 

# Directorio de tus funciones de Netlify.
# La ruta es relativa a la "Base directory" de Netlify.
[functions]
  directory = "netlify/functions"