# netlify.toml
[build]
  # El punto '.' indica que los archivos a desplegar están en la raíz del repositorio.
  publish = "." 
  # Deja el comando vacío si no hay un proceso de construcción
  # que compile tus archivos (como con React, Vue, etc.).
  command = "" 

# Configuración para tus funciones de Netlify.
# La ruta es relativa a la raíz del repositorio.
[functions]
  directory = "netlify/functions"