# netlify.toml

[build]
  command = "npm install && npm run generate-posts"
  publish = "."

# Añade esta sección para el plugin del sitemap (mejora de SEO)
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    baseUrl = "https://www.portugalapoia.com" # Asegúrate de que este es tu dominio