# netlify.toml
[build]
  # El directorio de publicación es la raíz de tu repositorio,
  # donde están tus archivos HTML, CSS, JS directamente.
  publish = "portugalapoia" 
  # No hay un comando de construcción necesario para este tipo de proyecto estático.
  command = "" 

# Configuración para tus funciones de Netlify, si las tienes.
# Según tus archivos, tienes la carpeta 'netlify/functions'.
[functions]
  directory = "portugalapoia/netlify/functions"