# Este bloque define la configuración general para TODAS las funciones.
# Solo puede aparecer UNA VEZ en todo el fichero.
[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

# Para programar una función específica, se hace de esta manera.
# La siguiente línea ha sido comentada para desactivar la limpieza automática.
# [functions.cleanup-expired]
#   schedule = "0 3 * * *"

[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
# Este plugin ayuda a generar un sitemap, pero no es esencial para el blog.

[[plugins]]
package = "netlify-cms-json-collections"

[plugins.inputs]
collections = [
  {
    name = "blog",
    path = "/blog/index.json"
  }
]