# netlify.toml
[build]
  # Indica que los archivos a desplegar están en la "Base directory"
  # que se configura en el panel de Netlify.
  publish = "." 
  
  # Deja el comando vacío si no hay un proceso de construcción.
  command = "" 

# Configuración del directorio de tus funciones de Netlify.
# La ruta es relativa a la "Base directory".
[functions]
  directory = "netlify/functions"