[build]
  publish = "/"
  command = ""

# --- CÓDIGO FINAL Y CORRECTO para netlify.toml ---

# Este bloque define la configuración general para TODAS las funciones.
# Solo puede aparecer UNA VEZ en todo el fichero.
[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

# Para programar una función específica, se hace de esta manera.
# Esto le dice a Netlify: "Dentro de tus funciones, la que se llama 
# 'cleanup-expired' tiene una configuración especial de horario".
[functions.cleanup-expired]
  schedule = "0 3 * * *"