# --- CÓDIGO FINAL Y CORRECTO para netlify.toml ---
# Este bloque define la configuración general para TODAS las funciones.
# Solo puede aparecer UNA VEZ en todo el fichero.
[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

# A partir de aquí, usamos [[functions]] (con dobles corchetes)
# para configurar cada función de forma individual.

# Función #1: Se activa cuando se crea una sumisión de formulario
[[functions]]
  name = "submission-created"

# Función #2: También se activa cuando se crea una sumisión de formulario
[[functions]]
  name = "submission-notification"

# Función #3: Se activa según un horario (cron job)
[[functions]]
  name = "cleanup-expired"
  schedule = "0 3 * * *"