# --- CÓDIGO FINAL Y CORRECTO para netlify.toml ---

# Este bloque define la configuración general para TODAS las funciones.
# Solo puede aparecer UNA VEZ en todo el fichero.
[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

# La función programada es la única que necesita una configuración individual.
# Las otras (submission-created, submission-notification) son automáticas.
[[functions]]
  name = "cleanup-expired"
  schedule = "0 3 * * *"