# netlify.toml
# Este archivo DEBE estar en la raíz de tu repositorio de Git.

[build]
  # 'publish = "portugalapoia"' le dice a Netlify que los archivos de tu sitio
  # listos para desplegar se encuentran dentro de la carpeta 'portugalapoia' del repositorio.
  publish = "portugalapoia" 

  # 'command = ""' indica que no hay un comando de construcción específico
  # que Netlify deba ejecutar, ya que tus archivos ya están listos.
  command = "" 

# Configuración del directorio para las funciones de Netlify.
# La ruta es relativa a la raíz del repositorio.
# Esto significa que tus funciones se esperan en 'tu-repositorio/portugalapoia/netlify/functions'.
[functions]
  directory = "portugalapoia/netlify/functions"