backend:
  name: github
  repo: Helder8a/portugalapoia # Asegúrate de que este sea tu usuario/repositorio
  branch: main
  publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "conteudos"
    label: "Conteúdos das Páginas"
    files:
      # --- ESTA ES LA SECCIÓN AÑADIDA Y CORREGIDA ---
      - file: "_dados/blog.json"
        label: "Publicações do Blog"
        name: "blog"
        fields:
          - name: "posts"
            label: "Artigos do Blog"
            widget: "list"
            fields:
              - {label: "ID do Post", name: "id", widget: "string", hint: "ID único para o post. Ex: BLOG-001"}
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Data de Publicação", name: "date", widget: "datetime"}
              - {label: "Imagem de Destaque", name: "image", widget: "image"}
              - label: "Categoria"
                name: "category"
                widget: "select"
                options: ["saude", "turismo", "educacao", "habitacao", "emprego"]
              - {label: "Resumo", name: "summary", widget: "text"}
              - {label: "Corpo do Artigo (aceita vídeos)", name: "body", widget: "markdown"}
      # --- EL RESTO DE TUS ARCHIVOS PERMANECE IGUAL ---
      - file: "_dados/empregos.json"
        # ...
      - file: "_dados/doacoes.json"
        # ...
      - file: "_dados/servicos.json"
        # ...
      - file: "_dados/habitacao.json"
        # ...
      - file: "_dados/homepage.json"
        # ...