# --- Configuración del Backend ---
# Usamos git-gateway para una mejor integración con Netlify
backend:
  name: git-gateway
  branch: main

# --- Dónde guardar las imágenes ---
media_folder: "images/uploads"
public_folder: "/images/uploads"

# --- Colecciones de Contenido ---
collections:
  # --- CONTENIDOS DE PÁGINAS (Esta sección se mantiene como la tenías) ---
  - name: "conteudos"
    label: "Conteúdos das Páginas"
    files:
      - file: "_dados/empregos.json"
        label: "Vagas de Emprego"
        name: "empregos"
        fields:
          - { label: "ID (Ex: EMP-033)", name: "id", widget: "string" }
          - { label: "Título da Vaga", name: "titulo", widget: "string" }
          - { label: "Localização", name: "localizacao", widget: "string" }
          - { label: "Descrição", name: "descricao", widget: "text" }
          - { label: "Tel", name: "contato", widget: "string", required: false }
          - { label: "Email", name: "link_contato", widget: "string", hint: "Coloque o email no formato mailto:exemplo@email.com", required: false }
          - { label: "Data de Publicação", name: "data_publicacao", widget: "date", format: "YYYY-MM-DD", required: false }
          - { label: "Data de Vencimento", name: "data_vencimento", widget: "date", format: "YYYY-MM-DD", required: false }
      # ... (Aquí irían las demás secciones: doacoes, servicos, habitacao)

  # --- COLECCIÓN DEL BLOG (VERSIÓN FINAL Y CORREGIDA) ---
  - name: "blog"
    label: "Publicaciones del Blog"
    folder: "_posts"  # <-- APUNTA A LA CARPETA CORRECTA
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título del Post", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "thumbnail", widget: "image", required: false } # Previene errores
      - { label: "Corpo do Post", name: "body", widget: "markdown", required: false, default: "" } # LA CLAVE DEFINITIVA para evitar el error