# --- admin/config.yml ---

# Configuración del Backend
backend:
  name: github
  repo: Helder8a/portugalapoia # Repositorio de GitHub (ya está correcto)
  branch: main
  publish_mode: editorial_workflow # Permite guardar borradores

# Dónde guardar las imágenes
media_folder: "images/uploads"
public_folder: "/images/uploads"

# Colecciones de Contenido (AQUÍ ESTÁ LA MAGIA)
collections:
  # --- Colección ÚNICA y MEJORADA para el Blog ---
  - name: "blog"
    label: "Blog"
    folder: "_blog" # Guarda los artículos en una nueva carpeta _blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Genera un nombre de archivo limpio
    fields:
      - { label: "Título del Post", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Doações", "Emprego", "Habitação", "Educação", "Turismo"] }
      - { label: "Imagem de Destaque", name: "thumbnail", widget: "image" }
      - { label: "Corpo do Post (Markdown)", name: "body", widget: "markdown" }
      # --- Campos para SEO Automático ---
      - name: "seo"
        label: "SEO (Otimização para Buscadores)"
        widget: "object"
        fields:
          - { label: "Título para SEO (Máx 60 caracteres)", name: "seo_title", widget: "string", required: false }
          - { label: "Meta Descrição (Máx 155 caracteres)", name: "meta_description", widget: "text", required: false }
          - { label: "Palavras-chave (separadas por vírgula)", name: "keywords", widget: "string", required: false }

  # Mantengo tu colección antigua por si la necesitas para otras cosas.
  # Si solo vas a usar el panel para el blog, puedes borrar esta parte ("conteudos").
  - name: "conteudos"
    label: "Conteúdos das Páginas (Antigo)"
    files:
      - file: "_dados/empregos.json"
        label: "Vagas de Emprego"
        name: "empregos"
        fields:
          - {label: "Lista de Vagas", name: "vagas", widget: "list", fields: [{label: "ID", name: "id", widget: "string"}, {label: "Título da Vaga", name: "titulo", widget: "string"}]}