# --- Configuración del Backend ---
backend:
  name: git-gateway
  branch: main

# --- Dónde guardar las imágenes ---
media_folder: "images/uploads"
public_folder: "/images/uploads"

# --- Colección para el Blog (CORREGIDA Y FINAL) ---
collections:
  - name: "blog"
    label: "Publicaciones del Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título del Post", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "thumbnail", widget: "image", required: false }
      - { label: "Corpo do Post", name: "body", widget: "markdown", required: false, default: "" } # <-- CAMBIO CLAVE: Añadido 'default: ""'