backend:
  name: github
  repo: Helder8a/portugalapoia # Reemplaza con tu repo
  branch: main
  publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images/uploads"

# Colecciones de Contenido (SECCIONES CORREGIDAS)
collections:
  - name: "doacoes"
    label: "Pedidos de Doação"
    files:
      - file: "_dados/doacoes.json"
        label: "Lista de Pedidos"
        name: "pedidos"
        fields:
          - {label: Lista de Pedidos, name: pedidos, widget: list, fields: [
              {label: ID (Ex: DOA-004), name: id, widget: string},
              {label: "Título do Pedido", name: titulo, widget: string},
              {label: Localização, name: localizacao, widget: string},
              {label: Descrição, name: descricao, widget: text},
              {label: "É Urgente?", name: urgente, widget: boolean, default: false},
              {label: "Imagem (Opcional)", name: imagem, widget: image, required: false},
              {label: Tel, name: contato, widget: string},
              {label: Email, name: link_contato, widget: string, hint: "Coloque o email no formato mailto:exemplo@email.com"},
              {label: "Data de Publicação", name: data_publicacao, widget: date, format: "YYYY-MM-DD", required: false},
              {label: "Data de Vencimento", name: data_vencimento, widget: date, format: "YYYY-MM-DD", required: false}
            ]}

  - name: "empregos"
    label: "Vagas de Emprego"
    files:
      - file: "_dados/empregos.json"
        label: "Lista de Vagas"
        name: "vagas"
        fields:
          - {label: "Lista de Vagas", name: vagas, widget: list, fields: [
              {label: "ID (Ex: EMP-033)", name: id, widget: string},
              {label: "Título da Vaga", name: titulo, widget: string},
              {label: Localização, name: localizacao, widget: string},
              {label: Descrição, name: descricao, widget: text},
              {label: Tel, name: contato, widget: string, required: false},
              {label: Email, name: link_contato, widget: string, hint: "Coloque o email no formato mailto:exemplo@email.com", required: false},
              {label: "Data de Publicação", name: data_publicacao, widget: date, format: "YYYY-MM-DD", required: false},
              {label: "Data de Vencimento", name: data_vencimento, widget: date, format: "YYYY-MM-DD", required: false}
            ]}

  - name: "servicos"
    label: "Ofertas de Serviço"
    files:
      - file: "_dados/servicos.json"
        label: "Lista de Serviços"
        name: "servicos"
        fields:
          - {label: "Lista de Serviços", name: servicos, widget: list, fields: [
              {label: "ID (Ex: SER-004)", name: id, widget: string},
              {label: "Logo da Empresa (Opcional)", name: logo_empresa, widget: image, required: false},
              {label: "Título do Serviço", name: titulo, widget: string},
              {label: "Valor do Serviço (Opcional)", name: valor_servico, widget: string, required: false, hint: "Ex: 50€, A combinar, Gratuito"},
              {label: Localização, name: localizacao, widget: string},
              {label: Descrição, name: descricao, widget: text},
              {label: Tel, name: contato, widget: string},
              {label: Email, name: link_contato, widget: string, hint: "Coloque o email no formato mailto:exemplo@email.com"},
              {label: "Data de Publicação", name: data_publicacao, widget: date, format: "YYYY-MM-DD", required: false},
              {label: "Data de Vencimento", name: data_vencimento, widget: date, format: "YYYY-MM-DD", required: false}
            ]}

  - name: "habitacao"
    label: "Anúncios de Habitação"
    files:
      - file: "_dados/habitacao.json"
        label: "Lista de Anúncios"
        name: "anuncios"
        fields:
          - {label: "Lista de Anúncios", name: anuncios, widget: list, fields: [
              {label: "ID (Ex: HAB-007)", name: id, widget: string},
              {label: "Título do Anúncio", name: titulo, widget: string},
              {label: Localização, name: localizacao, widget: string},
              {label: Descrição, name: descricao, widget: text},
              {label: Tel, name: contato, widget: string},
              {label: Email, name: link_contato, widget: string, hint: "Coloque o email no formato mailto:exemplo@email.com"},
              {label: "Data de Publicação", name: data_publicacao, widget: date, format: "YYYY-MM-DD", required: false},
              {label: "Data de Vencimento", name: data_vencimento, widget: date, format: "YYYY-MM-DD", required: false}
            ]}

  - name: "blog"
    label: "Publicações do Blog"
    files:
      - file: "_dados/blog.json"
        label: "Lista de Publicações"
        name: "posts"
        fields:
          - {label: "Lista de Publicações", name: posts, widget: list, fields: [
              {label: "Título da Publicação", name: titulo, widget: string},
              {label: "Data de Publicação", name: data, widget: date, format: "YYYY-MM-DD"},
              {label: "Imagem de Destaque", name: imagem, widget: image, required: false},
              {label: Categoria, name: categoria, widget: select, options: ["Doações", "Emprego", "Serviços", "Habitação", "Turismo", "Educação"]},
              {label: "Corpo da Publicação", name: corpo, widget: markdown}
            ]}