# --- Configuración del Backend ---
# Conexión con tu repositorio de GitHub
backend:
  name: git-gateway
  branch: main # Asegúrate de que esta es tu rama principal

# --- Dónde guardar las imágenes que subas desde el panel ---
media_folder: "images/uploads"
public_folder: "/images/uploads"

# --- Colección para el Blog (CORREGIDA) ---
collections:
  - name: "blog"
    label: "Publicaciones del Blog"
    folder: "_posts" # <-- CORRECCIÓN 1: Cambiado de _blog a _posts para que coincida con tu blog.html
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título del Post", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "thumbnail", widget: "image", required: false } # Hecho opcional
      - { label: "Corpo do Post", name: "body", widget: "markdown", required: false } # <-- CORRECCIÓN 2: Añadido 'required: false' para evitar el error al guardar.