# --- Configuração do Backend ---
backend:
  name: git-gateway # Esto conecta el panel con Netlify Identity/Git Gateway
  branch: main

# --- Dónde guardar las imágenes ---
media_folder: "images/uploads"
public_folder: "/images/uploads"

# --- Colección del Blog ---
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts" # La carpeta donde se guardan los artículos
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título da Publicação", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "thumbnail", widget: "image" }
      - { label: "Corpo da Publicação", name: "body", widget: "markdown" }