# --- Configuración del Backend ---
backend:
  name: github
  repo: Helder8a/portugalapoia
  branch: main

# --- Dónde guardar las imágenes que subas desde el panel ---
media_folder: "images/uploads"
public_folder: "/images/uploads"

# --- Colecciones de Contenido (Las secciones editables de tu web) ---
collections:
  - name: "conteudos"
    label: "Conteúdos das Páginas"
    files:
      # --- Editor para la página de Empleos ---
      - file: "_dados/empregos.json"
        label: "Vagas de Emprego"
        name: "empregos"
        fields:
          - label: "Lista de Vagas"
            name: "vagas"
            widget: "list"
            fields:
              - { label: "ID (Ex: EMP-033)", name: "id", widget: "string" }
              - { label: "Título da Vaga", name: "titulo", widget: "string" }
              - { label: "Localização", name: "localizacao", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - { label: "Tel", name: "contato", widget: "string" }
              - { label: "Email", name: "link_contato", widget: "string", hint: "Coloque o email no formato mailto:exemplo@email.com" }

      # --- Editor para la página de Donaciones ---
      - file: "_dados/doacoes.json"
        label: "Pedidos de Doação"
        name: "doacoes"
        fields:
          - label: "Lista de Pedidos"
            name: "pedidos"
            widget: "list"
            fields:
              - { label: "ID (Ex: DOA-004)", name: "id", widget: "string" }
              - { label: "Título do Pedido", name: "titulo", widget: "string" }
              - { label: "Localização", name: "localizacao", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - { label: "É Urgente?", name: "urgente", widget: "boolean", default: false }
              - { label: "Imagem (Opcional)", name: "imagem", widget: "image", required: false }
              - { label: "Tel", name: "contato", widget: "string" }
              - { label: "Email", name: "link_contato", widget: "string", hint: "Coloque o email no formato mailto:exemplo@email.com" }

      # --- Editor para la página de Servicios  ---
      - file: "_dados/servicos.json"
        label: "Ofertas de Serviço"
        name: "servicos"
        fields:
          - label: "Lista de Serviços"
            name: "servicos"
            widget: "list"
            fields:
              - { label: "ID (Ex: SER-004)", name: "id", widget: "string" }
              - { label: "Logo da Empresa (Opcional)", name: "logo_empresa", widget: "image", required: false }
              - { label: "Título do Serviço", name: "titulo", widget: "string" }
              - { label: "Valor do Serviço (Opcional)", name: "valor_servico", widget: "string", required: false, hint: "Ex: 50€, A combinar, Gratuito" }
              - { label: "Localização", name: "localizacao", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - { label: "Tel", name: "contato", widget: "string" }
              - { label: "Email", name: "link_contato", widget: "string", hint: "Coloque o email no formato mailto:exemplo@email.com" }

      # --- Editor para la página de Vivienda ---
      - file: "_dados/habitacao.json"
        label: "Anúncios de Habitação"
        name: "habitacao"
        fields:
          - label: "Lista de Anúncios"
            name: "anuncios"
            widget: "list"
            fields:
              - { label: "ID (Ex: HAB-007)", name: "id", widget: "string" }
              - { label: "Título do Anúncio", name: "titulo", widget: "string" }
              - { label: "Localização", name: "localizacao", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - { label: "Tel", name: "contato", widget: "string" }
              - { label: "Email", name: "link_contato", widget: "string", hint: "Coloque o email no formato mailto:exemplo@email.com" }

  # --- Colección separada para el Blog ---
  - name: "blog"
    label: "Blog"
    folder: "_blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título do Post", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "thumbnail", widget: "image" }
      - { label: "Corpo do Post", name: "body", widget: "markdown" }