# --- COLECCIÓN DEL BLOG (VERSIÓN FINAL Y CORREGIDA) ---
  - name: "blog"
    label: "Publicaciones del Blog"
    folder: "_posts"  # <-- Correcto: apunta a _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título del Post", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "thumbnail", widget: "image", required: false }
      - { label: "Corpo do Post", name: "body", widget: "markdown", required: false, default: "" } # <-- Correcto: previene errores