backend:
  name: github
  repo: Helder8a/portugalapoia 
  branch: main
  publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_dados/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data de Publicação", name: "date", widget: "datetime"}
      - {label: "Imagem de Destaque", name: "image", widget: "image"}
      - {label: "Categoria", name: "category", widget: "select", options: ["saude", "turismo", "educacao", "habitacao", "emprego"]}
      - {label: "Resumo", name: "summary", widget: "text"}
      - {label: "Corpo do Artigo (aceita vídeos)", name: "body", widget: "markdown"}
  - name: "galeria"
    label: "Galeria de Imagens"
    folder: "_dados/galeria"
    create: true
    fields:
      - {label: "Título da Imagem", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Ficheiro da Imagem", name: "image", widget: "image"}
      - {label: "Legenda", name: "caption", widget: "string", hint: "Uma descrição curta para a imagem."}
  - name: "empregos"
    label: "Vagas de Emprego"
    folder: "_dados/empregos"
    create: true
    fields:
      - {label: "ID (Ex: EMP-033)", name: "id", widget: "string"}
      - {label: "Título da Vaga", name: "titulo", widget: "string"}
      - {label: "Localização", name: "localizacao", widget: "string"}
      - {label: "Descrição", name: "descricao", widget: "text"}
      - {label: "Tel", name: "contato", widget: "string", required: false}
      - {label: "Email", name: "link_contato", widget: "string", hint: "Coloque o email no formato mailto:exemplo@email.com", required: false}
      - {label: "Data de Publicação", name: "data_publicacao", widget: "date", format: "YYYY-MM-DD", required: false}
      - {label: "Data de Vencimento", name: "data_vencimento", widget: "date", format: "YYYY-MM-DD", required: false}
  - name: "doacoes"
    label: "Pedidos de Doação"
    folder: "_dados/doacoes"
    create: true
    fields:
      - {label: "ID (Ex: DOA-004)", name: "id", widget: "string"}
      - {label: "Título do Pedido", name: "titulo", widget: "string"}
      - {label: "Localização", name: "localizacao", widget: "string"}
      - {label: "Descrição", name: "descricao", widget: "text"}
      - {label: "É Urgente?", name: "urgente", widget: "boolean", default: false}
      - {label: "Imagem (Opcional)", name: "imagem", widget: "image", required: false}
      - {label: "Tel", name: "contato", widget: "string"}
      - {label: "Email", name: "link_contato", widget: "string", hint: "Coloque o email no formato mailto:exemplo@email.com"}
      - {label: "Data de Publicação", name: "data_publicacao", widget: "date", format: "YYYY-MM-DD", required: false}
      - {label: "Data de Vencimento", name: "data_vencimento", widget: "date", format: "YYYY-MM-DD", required: false}
  - name: "servicos"
    label: "Ofertas de Serviço"
    folder: "_dados/servicos"
    create: true
    fields:
      - {label: "ID (Ex: SER-004)", name: "id", widget: "string"}
      - {label: "Logo da Empresa (Opcional)", name: "logo_empresa", widget: "image", required: false}
      - {label: "Título do Serviço", name: "titulo", widget: "string"}
      - {label: "Valor do Serviço (Opcional)", name: "valor_servico", widget: "string", required: false, hint: "Ex: 50€, A combinar, Gratuito"}
      - {label: "Localização", name: "localizacao", widget: "string"}
      - {label: "Descrição", name: "descricao", widget: "text"}
      - {label: "Tel", name: "contato", widget: "string"}
      - {label: "Email", name: "link_contato", widget: "string", hint: "Coloque o email no formato mailto:exemplo@email.com"}
      - {label: "Data de Publicação", name: "data_publicacao", widget: "date", format: "YYYY-MM-DD", required: false}
      - {label: "Data de Vencimento", name: "data_vencimento", widget: "date", format: "YYYY-MM-DD", required: false}
  - name: "habitacao"
    label: "Anúncios de Habitação"
    folder: "_dados/habitacao"
    create: true
    fields:
      - {label: "ID (Ex: HAB-007)", name: "id", widget: "string"}
      - {label: "Título do Anúncio", name: "titulo", widget: "string"}
      - {label: "Valor do Anúncio", name: "valor_anuncio", widget: "string", required: false, hint: "Ex: 450€/mês"}
      - {label: "Localização", name: "localizacao", widget: "string"}
      - {label: "Descrição", name: "descricao", widget: "text"}
      - {label: "Imagens do Imóvel", name: "imagens", widget: "list", required: false, fields: [{label: "Imagem", name: "imagem_url", widget: "image"}]}
      - {label: "Tel", name: "contato", widget: "string", required: false}
      - {label: "Email", name: "link_contato", widget: "string", required: false}
      - {label: "Data de Publicação", name: "data_publicacao", widget: "date", format: "YYYY-MM-DD", required: false}
      - {label: "Data de Vencimento", name: "data_vencimento", widget: "date", format: "YYYY-MM-DD", required: false}
  - name: "paginas" # Colección para archivos de página específicos
    label: "Páginas"
    files:
      - file: "_dados/homepage.json"
        label: "Página Principal"
        name: "homepage"
        fields:
          - {label: "Título Principal", name: "hero_title", widget: "string"}
          - {label: "Subtítulo", name: "hero_subtitle", widget: "string"}
          - {label: "Textos dos Contadores de Impacto", name: "impact_counters", widget: "object", fields: [{label: "Texto para Doações", name: "doacoes_text", widget: "string"}, {label: "Texto para Emprego", name: "emprego_text", widget: "string"}, {label: "Texto para Total de Anúncios", name: "total_text", widget: "string"}]}
      - file: "_dados/footer.json" # Archivo para gestionar el footer
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Copyright Text", name: "copyright", widget: "string" }
          - label: "Social Media Links"
            name: "social_links"
            widget: "list"
            fields:
              - { label: "URL", name: "url", widget: "string" }
              - label: "Icon"
                name: "icon"
                widget: "select"
                options: ["facebook", "instagram", "twitter", "linkedin"]