backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment the following lines to enable local development
# local_backend: true

media_folder: "images/uploads" # Folder where user uploaded files should be stored

collections:
  - name: "blog"
    label: "Blog"
    folder: "_dados/blog_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "string" } # <--- CAMBIO AÑADIDO AQUÍ
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem de Destaque", name: "image", widget: "image" }
      - { label: "Categoria", name: "category", widget: "select", options: ["saude", "habitacao", "emprego", "turismo", "educacao"] }
      - { label: "Resumo", name: "summary", widget: "text" }
      - { label: "Corpo", name: "body", widget: "markdown" }
  - name: "homepage"
    label: "Página Inicial"
    folder: "_dados"
    create: false
    slug: "homepage"
    fields:
      - { label: "Título Principal (Hero)", name: "hero_title", widget: "string" }
      - { label: "Subtítulo (Hero)", name: "hero_subtitle", widget: "string" }
      - name: "impact_counters"
        label: "Contadores de Impacto"
        widget: "object"
        fields:
          - { label: "Texto Doações", name: "doacoes_text", widget: "string" }
          - { label: "Texto Emprego", name: "emprego_text", widget: "string" }
          - { label: "Texto Total", name: "total_text", widget: "string" }